preimage:
  result_dir: "result_dir"
  over_approx: True
  under_approx: False
  threshold: 1.1
  label: 0
model:
  name:  auto_park_20
  path: "model_dir/model_auto_park_auto_park_model_20.pt"
data:
  dataset: auto_park
  num_outputs: 4
  start: 0
  end: 1
specification:
  type: 'bound'
  robustness_type: "verified-acc"
solver:
  batch_size: 50
bab:
  branching:
    method: "preimg"
    input_split:
      enable: True