preimage:
  sample_dir: "sample_dir"
  result_dir: "result_dir"
  over_approx: False
  under_approx: True
  threshold: 0.75
  label: 0
model:
  name:  "cartpole"
  onnx_path: "model_dir/cartpole.onnx"
  path: None
specification:
  type: 'bound'  
  robustness_type: "verified-acc"
data:
  dataset: cartpole
  num_outputs: 2
  start: 0
  end: 1
solver:
  batch_size: 50
bab:
  branching:
    branching_method: "preimg"
    input_split:
      enable: True
