preimage:
  threshold: 0.75
  label: 0
  runner_up: 1
model:
  name:  None
  onnx_path: "/home/xiyue/LinInv/model_dir/cartpole.onnx"
  path: None
  
data:
  dataset: cartpole
  num_outputs: 2
  start: 0
  end: 1
specification:
  type: 'bound'
solver:
  batch_size: 50
bab:
  branching:
    input_split:
      enable: True
